spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-patient-meadow-a1sqfz0o-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require}
    username: ${DB_USERNAME:neondb_owner}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect